### ISSUE TITLE
Local cache of recordings

### ISSUE THREAD

**Issue by Prefect47** [MythTV-Clients/MythTV-Android-Frontend#124]
Since we are dealing with high-bitrate streams it would be nice to have a local cache of recordings and/or HLS streams that the user can setup and manage, so that they can be watched even in places with no or slow network connectivity.

**Comment by dmfrey** [comment]
This is a tough one.

Some of the recordings in native format can be very large, and it would
take a considerable time to download these recordings.  Also, we are not
managing how the player handles buffering/caching.  That is up to the
player itself.  Also, no matter what we do, mpeg2, especially HD
recordings, will always play sluggishly on android until hardware
acceleration can be added.  The best result would be to perform a transcode
on the backend to knock the file size down, remove commercials (if
desired), and ultimately transcode to h264, which android can use
hardware acceleration to playback.

That being said, the reason for HLS is to alleviate some of the issues
mentioned above.  The playback profiles are there to help in bandwidth
limited environments.  You could always pre-hls transcode with the new
features so that they streams are small and available for when you are on
an away network.

Does this help?  Does it clarify the issue?

On Sun, Mar 3, 2013 at 5:43 AM, Prefect47 notifications@github.com wrote:

> Since we are dealing with high-bitrate streams it would be nice to have a
> local cache of recordings and/or HLS streams that the user can setup and
> manage, so that they can be watched even in places with no or slow network
> connectivity.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/124
> .

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
No response in > 30 days, closing. Please reopen if needed.
