### ISSUE TITLE
Scan Network hangs forever after reinstall

### ISSUE THREAD

**Issue by UlfGran** [MythTV-Clients/MythTV-Android-Frontend#247]
After doing uninstall and reinstall of the app, the "Scan network" function for discovering backend will hang with "Please Wait" message seemingly forever. The backend is running, avahi is running, the Scan network function worked only a few days ago, and if I add the backend adress manually, playback of recordings works. So why did "Scan network" stop working? App version is 1.10.1, backend version is 0.27. The device is a Nexus 7 with Android 4.4.2. Even if the problem would be on the backend side, it is still an issue that there seems to be no timeout or user feedback when the Scan Network function does not find anything.

**Comment by billmeek** [comment]
Thanks for including all the details in your question!

Late in the MythTV 0.27 development cycle, the name used for Bonjour was changed from
_mythbackend-master to simply _mythbackend plus a TXT field of master (or slave.)

MAF 1.10 doesn't know about this. The beta 1.20 does and the ability to cancel the scan
was also added. There was also a change in 0.27 that makes the Recording Rules screen
fail, which is fixed in 1.20.  Looks like you (plus 'lund') are already a member of the beta
testers group, so you should be able to download that.

If you're curious, look for a line containing following in your backend log:

```
Bonjour: Service registration complete: name 'Mythbackend on <yourHostName>' type '_mythbackend._tcp.' domain: 'local.'
```

**Comment by UlfGran** [comment]
Thanks for a quick reply. So it seems my backend was updated since I last did the Network scan. Yes, there is a line similar to yours in the backend log. The reason I did the reinstall of the app in the first place was because I was hoping to get the 1.20 version, apparently I do not quite understand how to download the beta-test version. Could you please help with that? Just doing a reinstall from Google Play doesn't do it...

**Comment by billmeek** [comment]
Unfortunately, I'm not a good source for why you're not getting the 1.20.6 release. I know
others on the Google Groups list have mentioned similar problems. I can only suggest
going to Applications->MythTV Android Frontend->Force stop, Clear cache, Clear data
and Uninstall. I'm suggesting that rather than the Reinstall (which I don't see when I go
to Google Play.) If that doesn't work, perhaps asking in the Google Group will help (there
are a lot more users there than here.)

**Comment by billmeek** [comment]
For the archive, checking: https://play.google.com/apps/testing/org.mythtv must 
display "You are a tester". That solved the inability to get the beta code. Closing
the issue.

**Comment by UlfGran** [comment]
Well, what you suggest was exactly what I did, and I called that Reinstall, even though there is no such button on Google Play. I have now asked at the Google group, and the problem is solved. Thanks for your help.
