### ISSUE TITLE
Icon disappered

### ISSUE THREAD

**Issue by cormanaz** [MythTV-Clients/MythTV-Android-Frontend#253]
I upgraded to the latest release and the icon disappeared frome the desktop.  I can still launch From the play store app open button. This is on a Galaxy Note 10.1 2014 running Android 4.3.

**Comment by billmeek** [comment]
This is normal as I believe you switched from 1.10.1 to the Beta 1.20.6. Press the application icon and drag the MAF icon to the desired location on your screen. When 1.20.7 is released, I believe you _won't_ see this issue. I suspect this will happen again when 1.20.x is changed from Beta to a 'normal' release.

**Comment by netwolfuk** [comment]
I've seen this behaviour before where the play store app does not recreate the icon in your apps area on your device. You can't drag and drop from apps list to the screen because it does not exist there. As the op said finding the app inside the play store app is the only way to launch it.

I ended up having to reboot the device before the icon appeared as an app on my device. I believe it happens when the play store app crashes during an app upgrade. It can happen with any app upgrade.
