### ISSUE TITLE
The selected Backend profile's host isn't responding

### ISSUE THREAD

**Issue by dmz006** [MythTV-Clients/MythTV-Android-Frontend#254]
Hello
I installed the beta version 1.20.6 and things worked great for the frontend for about 3 weeks, then about a week ago I started getting the profile's host isn't responding message. 

I have restarted mythbackend and nothing I seem to do anything.  

I have not done any debugging on this app yet so let me know how I can get more information and I'll be happy to get it.

When I capture the network traffic for the profile connection it appears to work but once it finishes receiving the status message the client is not able to process it.

```
T phone:38947 -> mythbox:6544 [AP]
  GET /Myth/GetHostName HTTP/1.1
Connection: Close
Accept-Encoding: identity
User-Agent: MAF
Host: mythbox:6544

T mythbox:6544 -> phone:38947 [AP]
  HTTP/1.1 200 OK..Date: 13 Mar 2014 04:38:11
Server: Linux 3.11.0-15-generic, UPnP/1.0, MythTV 0.27.20130902-1
Accept-Ranges: bytes
Cache-Control: no-cache="Ext", max-age = 5000
ETag: "da39a3ee5e6b4b0d3255bfef95601890afd80709"
Connection: Close
Content-Type: text/xml
Content-Length: 68

<?xml version="1.0" encoding="UTF-8"?><String>johnnyjohnny</String>.

T phone:38948 -> mythbox:6544 [AP]
  GET /Myth/GetHostName HTTP/1.1
Connection: Close
Accept-Encoding: identity
User-Agent: MAF
Host: mythbox:6544

T mythbox:6544 -> phone:38948 [AP]
  HTTP/1.1 200 OK
Date: 13 Mar 2014 04:38:12
Server: Linux 3.11.0-15-generic, UPnP/1.0, MythTV 0.27.20130902-1
Accept-Ranges: bytes
Cache-Control: no-cache="Ext", max-age = 5000
ETag: "da39a3ee5e6b4b0d3255bfef95601890afd807 09"
Connection: Close
Content-Type: text/xml
Content-Length: 68

<?xml version="1.0" encoding="UTF-8"?><String>johnnyjohnny</String>.

T phone:38949 -> mythbox:6544 [AP]
  GET /Status/GetStatus HTTP/1.1..Accept: application/xml
Connection: Close
User-Agent: Services API
Content-Length: 0
Host: mythbox:6544
Accept-Encoding: gzip....                                                       

T mythbox:6544 -> phone:38949 [A]
  HTTP/1.1 200 OK
Date: 13 Mar 2014 04:38:13
Server: Linux 3.11.0-15-generic, UPnP/1.0, MythTV 0.27.20130902-1
Accept-Ranges: bytes
Cache-Control: no-cache="Ext", max-age = 5000
Content-Encoding: gzip
Connection: Close
Co ntent-Type: text/xml; charset="UTF-8"
Content-Length: 4125...............]
```

**Comment by billmeek** [comment]
Hi, this may be a tough one. The 1st thing I'd do is manually test the GetStatus message from your device's browser:

```
http://<yourMasterBackendIP>:6544/Status/GetStatus
```

I suspect that will work OK, but it's worth looking at the output.  The only thing that I can think of that would change is if you added a "Miscellaneous status application" script recently, but I've tested it and it worked for me.

Is your Master Backend's hostname really 'johnnyjohnny'? Since that's used as a MythTV profile name in its DB, I'm just curious if it's correct (there's nothing wrong with the name, I'm just making sure since your protocol refrences hostname 'mythbox'.) If you've chosen to set the hostname in the LocalHostName element in the config.xml file or an alias in /etc/hosts or DHCP..., then no problem.

There are three methods for collecting logs (in order of easiest to full development) here:

```
https://github.com/MythTV-Clients/MythTV-Android-Frontend/wiki/_Collecting-Log-Files
https://github.com/MythTV-Clients/MythTV-Android-Frontend/wiki/_Monitor-Environment-Setup
https://github.com/MythTV-Clients/MythTV-Android-Frontend/wiki/_Development-Environment-Setup
```

If it comes to this, then put the output in a pastebin of your choice and put a link to it here.

**Comment by billmeek** [comment]
No feedback in 1 month, closing. Please reopen if there's new data. Thanks!

**Comment by dmz006** [comment]
Sorry for the long delay; it seems that when I upgraded my mythbackend to ubuntu 14 it got whatever release the myth android needed and it's working again.  Now if I can only get the video to play...
