### ISSUE TITLE
MAF does not seem to retrieve recordings on 0.28

### ISSUE THREAD

**Issue by tekrantz** [MythTV-Clients/MythTV-Android-Frontend#258]
Just updated my backend to 0.28.  I cleared all MAF data.  MAF seems to fail to retrieve any recording data.

**Comment by billmeek** [comment]
Sorry. 0.28 doesn't exist, only 0.28-pre and there have been significant changes in the MythTV Services API since 0.27. As mentioned in the Play Store, this app only works with 0.25 through 0.27. MAF version 1.20.6 is in Beta (and also only supports 0.25-0.27.) If you build MAF from source, the 1.30 Alpha code exists, but you should understand that changes to 0.28-pre could break it and MAF fixes may not be easily/quickly implemented. The MythTV-Service-API is the underlying code that connects MAF to the backend and also must be built from source (v1.30.)
