### ISSUE TITLE
Settings allow different IP addresses. Different databases are not supported

### ISSUE THREAD

**Issue by billmeek** [MythTV-Clients/MythTV-Android-Frontend#83]
My Home backend is 192.168.10.204. My Away backend is 192.168.10.223.
Two different boxes.

If I use my Home setting and retrieve all updates, then switch to my Away
setting, the Home data remains. Neither the automatic nor the manual updates
get the Away data. This applies to the Recordings, Upcoming, Guide and 
Recording Rules screens.

Rather than guess, I'll let you decide if this is a single problem or four different
cases. Let me know how to proceed and I'll collect the data.

I'm marking this as a bug for now. Please correct to enhancement if it applies.

**Comment by dmfrey** [comment]
what you are saying is that the app should handle multiple backends that
each contain separate data, correct?

Not just the case where you are connection to the same backend multiple
ways (i.e. home via zeroconf, away via something like dyndns, etc.)

It would be considerable refactoring to the db schema at this time to allow
multiple different backends, but I agree that it should be possible.

What is the likelyhood of the general population having multiple, different
backends that they would want to connect the app too?

Can we mark this as an enhancement for now?

On Tue, Nov 20, 2012 at 12:25 AM, billmeek notifications@github.com wrote:

> My Home backend is 192.168.10.204. My Away backend is 192.168.10.223.
> Two different boxes.
> 
> If I use my Home setting and retrieve all updates, then switch to my Away
> setting, the Home data remains. Neither the automatic nor the manual
> updates
> get the Away data. This applies to the Recordings, Upcoming, Guide and
> Recording Rules screens.
> 
> Rather than guess, I'll let you decide if this is a single problem or four
> different
> cases. Let me know how to proceed and I'll collect the data.
> 
> I'm marking this as a bug for now. Please correct to enhancement if it
> applies.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/83.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
Yes, two hosts. One for production, one for testing. One has about 60 rules, the other has 6.

Based on my readings of the MythTV mailing lists and IRC channels, a number of users have
similar setups. Also there are those with virtual machines and chroot jails that keep multiple
versions. I have no idea how many do that and are Android users etc.

At the least, I need to add some text to the Wiki that explains the purpose of Home and Away
choices. Additionally, the same is probably true for the ability to add multiple Saved Profiles 
under Home and Away.

Is there a way for the application to detect that a different database has been selected and
prevent users from hurting themselves (e.g. with some warning message?)

**Comment by dmfrey** [comment]
Well, what I think has to happen is this:
1. each table row needs to be qualified with something from the location
   profile
   - either name or ip address, etc.
2. all queries need to be updated to accept the location profile so that it
   can be used in the queries.
3. All files downloaded need to be qualified with the same selection from 1
   - i.e. a program guide file should be <ip>_<date>.json instead of just
     <date>.json
   - This will go away once the content provider is used, but is still
     required right now
4. (optional) update the home location profile scanner to scan for all
   master backends on the network and allow them to be selected from a list
   - this last step really needs to be an enhancement
   - also, when either, home or away are blank, then maybe we should pop
     something up there as well that will auto configure it the first time

I think everything in the application would work as is except for the
program guide.  The recorded, upcoming and recording rules all refresh on a
periodic basis to get the current list of items from the backend and update
the local db.  It would just replace what it no longer knows about because
it assumes they are no longer available on the backend.

Let me know what you think.

Dan

On Tue, Nov 20, 2012 at 12:59 PM, billmeek notifications@github.com wrote:

> Yes, two hosts. One for production, one for testing. One has about 60
> rules, the other has 6.
> 
> Based on my readings of the MythTV mailing lists and IRC channels, a
> number of users have
> similar setups. Also there are those with virtual machines and chroot
> jails that keep multiple
> versions. I have no idea how many do that and are Android users etc.
> 
> At the least, I need to add some text to the Wiki that explains the
> purpose of Home and Away
> choices. Additionally, the same is probably true for the ability to add
> multiple Saved Profiles
> under Home and Away.
> 
> Is there a way for the application to detect that a different database has
> been selected and
> prevent users from hurting themselves (e.g. with some warning message?)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/83#issuecomment-10565456.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by billmeek** [comment]
I think it sounds like a huge change for an unknown number of users. Currently 1.
So out of  1000+ Play downloads, 349 Github and X building from source, that's 
something well under .07%

The root cause is my misunderstanding of the use of Home/Away and their multiple
profiles. That can be documented. I'd suggest that preventing those who choose to
access different databases can only be prevented in the application.

With both of my hosts up and my MAF data completely removed, I did a scan from
setup. Both of my boxes were found and labeled:

```
Mythbackend on mc1
Mythbackend on mc0
```

with the proper IP addresses. I would have no problem if this were closed as won't
fix although I'd prefer to see some defensive code added.

Bill

**Comment by dmfrey** [comment]
@billmeek working on implementing this now.  Going to add it before any new features get added because it kind of affects the overall db schema and table joins.  Hope to have something for you soon.

**Comment by billmeek** [comment]
Wow. If you've not coded it up, did you consider storing the files in 'per host' directories,
rather that modifying the file names to somehow reference the host (step 3 above?)

Also, in step 4, the Home scanner detects both of my boxes and then brings up the
edit window. In my case, I just pressed save. I didn't try cancel, but assume that would
be the method of 'rejecting' a found host.

**Comment by dmfrey** [comment]
step 3 would only be an interim measure.  hopefully the files will away
altogether and just be stored in the db.

step 4 was requested by Tom from mythbuntu and had a few other questions
about it.  There is an issue out there for it already.  I forget the number
offhand.  But basically if you click home and no locations are set,
automatically run the zeroconf and preconfigure if only one present.
 Otherwise, show a display that lets you select which one you want that was
autodetected.

the preferences screen also needs to be updated to allow for autodection to
return multiple entries and allow the user to select them.

On Tue, Nov 27, 2012 at 3:52 PM, billmeek notifications@github.com wrote:

> Wow. If you've not coded it up, did you consider storing the files in 'per
> host' directories,
> rather that modifying the file names to somehow reference the host (step 3
> above?)
> 
> Also, in step 4, the Home scanner detects both of my boxes and then brings
> up the
> edit window. In my case, I just pressed save. I didn't try cancel, but
> assume that would
> be the method of 'rejecting' a found host.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/MythTV-Clients/MythTV-Android-Frontend/issues/83#issuecomment-10776387.

## 

My Google Profile http://www.google.com/profiles/dmfrey

**Comment by dmfrey** [comment]
Except for the program guide, this should be pretty much complete.

**Comment by billmeek** [comment]
Update, running: mythtv-android-frontend-1.0.3-57-g8938730.

If I fire up both of my backends (and have no data in MAF) then when
I connect to one backend and load all data, all is A-OK.

When I then exit to initial screen and select  the opposite backend, the
data from the initial test remains (only testing Recordings/Upcommng/
Recording Rules.)

If I exit MAF and do a force stop on the application and restart it:

```
Upcoming still has the 1st tests data
Recording Rules are A-OK
Recordings are correct, however, the coverart and details from
    the 1st test (60 Minutes) remains until I select another show.
```

I had to use the refresh icon on the above tests to get the new data,
it wasn't updated automatically.

@dmfrey, it appears to me that significant changes were made and
it would make sense to create five new issues and gather data specific
to each of them (and close this issue.) Please let me know your preference.

The new issues would be:

```
Force stop required to get new data
Automatic updates not done when new backend is selected
Upcoming not updated
Stale coverart/details in Recordings 
Guide data not changed.
```

Bill

**Comment by dmfrey** [comment]
@billmeek where did we leave off on this?  Are all of these still issues? do they need to be created as issues?

**Comment by billmeek** [comment]
@dmfrey, Just retested. Yes, they're open. I wasn't clear about where you were
in development, but I'll take your comments as a go-ahead to open issues. I'll
start with just one as I have know idea if fixing one issue will fix them all.

I'm closing this and will reference it in related new issue(s) in case users read it
and want status.
